example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import login_user, logout_user, register, show_json, show_json_by_id, show_wishlist, show_wishlist_ajax, show_xml, show_xml_by_id, submit_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', submit_wishlist, name='generate_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from wishlist.models import BarangWishlist
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Ihza Dafa',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'last_login': request.COOKIES['last_login'],
    }
    
    return render(request, "wishlist_ajax.html", context)

def submit_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST['nama_barang']
        deskripsi = request.POST['deskripsi']
        harga_barang = request.POST['harga_barang']
        wishlist_instance = BarangWishlist(nama_barang=nama_barang, deskripsi=deskripsi, harga_barang=harga_barang)
        wishlist_instance.save()
        data = {
            "message": 'Successfully submitted'
        }
        json_object = json.dumps(data, indent = 4) 

        return JsonResponse(json.loads(json_object))
    return render(request, 'generate_wishlist.html')
        

def show_xml(request):
    data = BarangWishlist.objects.all()
    
    return HttpResponse(serializers.serialize('xml', data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    
    return HttpResponse(serializers.serialize('json', data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('json', data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('xml', data), content_type="application/xml")
    
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now())) # create last_login cookie and add it to response
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
    />

    {% block meta %} {% endblock meta %}
  </head>

  <body>
    {% block content %} {% endblock content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

wishlist/templates/generate_wishlist.html
{% extends 'base.html' %} {% block meta %}
<title>Generate Wishlist</title>

{% endblock meta %} {% block content %}

<div class="w-100 vh-100 d-flex justify-content-center align-items-center">
  <div
    class="d-flex flex-column align-items-center rounded-4 bg-light p-4 shadow-lg"
  >
    <h1>Generate Wishlist</h1>

    <form method="POST" action="" class="d-flex flex-column">
      {% csrf_token %}
      <div class="d-flex flex-column mb-2">
        <label for="nama_barang">Nama Barang</label>
        <input
          type="text"
          name="nama_barang"
          id="nama_barang"
          placeholder="Nama Barang"
          class="form-control"
        />
      </div>
      <div class="d-flex flex-column mb-2">
        <label for="harga_barang">Harga Barang</label>
        <input
          name="harga_barang"
          id="harga_barang"
          placeholder="Harga Barang"
          class="form-control"
        />
      </div>
      <div class="d-flex flex-column mb-2">
        <label for="deskripsi">Deskripsi</label>
        <input
          name="deskripsi"
          id="deskripsi"
          placeholder="Deskripsi"
          class="form-control"
        />
      </div>
      <button class="btn btn-success">Submit</button>
    </form>

    <span id="message"></span>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $('form').submit(function (event) {
      const formData = {
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
        nama_barang: $('#nama_barang').val(),
        harga_barang: parseInt($('#harga_barang').val()),
        deskripsi: $('#deskripsi').val(),
      };

      $.ajax({
        type: 'POST',
        url: '/wishlist/ajax/submit',
        data: formData,
        dataType: 'json',
        encode: true,
      }).done(function (data) {
        $('#message').text(data.message);
      });

      event.preventDefault();
    });
  });
</script>
{% endblock content %}

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>

{% endblock meta %}

{% block content %}
<nav class="navbar" style="background-color: rgb(171, 235, 22);">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1"> Selamat Datang!</span>
    </div>
</nav>


<div class = "login" style="text-align:center">

    <h1 style="margin-top: 25px">Login</h1>

    <form method="POST" action="" >
        {% csrf_token %}
        <table style="margin-left:auto;margin-right:auto; margin-top: 25px" class="table table-bordered w-auto">
            <tr>
                <td style="vertical-align: middle">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td style="vertical-align: middle">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <td><input class="btn btn-warning" type="submit" value="Login"></td>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" navbar-expand-lg bg-light" style="display: flex; justify-content: space-between;background-color: rgb(171, 235, 22)">
    <div class"" style"margin-left: 20px;">
        <h5>Nama: {{nama}}</h5>
    </div>

</nav>
    
<table class="table table-striped">
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
{% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
{% endfor %}

</table>
<h5>Sesi terakhir login: {{ last_login }}</h5>
<button types="button" class="btn btn-warning" style="margin-right: 20px;"><a href="{% url 'wishlist:logout' %}" style="color: black;">logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div>
      <a class="navbar-brand" href="#">Hello, {{user.get_username}}</a>
      <span>Last Login: {{ last_login }}</span>
    </div>
    <a href="{% url 'wishlist:generate_wishlist' %}" class="btn btn-success"
      >Add Task</a
    >
    <a href="{% url 'wishlist:logout' %}" class="btn btn-danger">Logout</a>
  </div>
</nav>

<div class="w-100 d-flex justify-content-center">
  <table class="table table-hover">
    <thead class="table-dark">
      <th>Nama Barang</th>
      <th>Harga Barang</th>
      <th>Deskripsi</th>
    </thead>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    <tbody id="table-body"></tbody>
  </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $.get('/wishlist/json', function (data) {
      data.map((singleData) =>
        $('#table-body').append(`<tr>
    <td>${singleData.fields.nama_barang}</td>
    <td>${singleData.fields.harga_barang}</td>
    <td>${singleData.fields.deskripsi}</td>
  </tr>`)
      );
    });
  });
</script>

{% endblock content %}